import Head from "next/head";
import { Counter } from "../feature/counter/Counter";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sticky Notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sticky.svg" />
      </Head>
      <Counter />
    </>
  );
}
